### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by JeanLouisMassei** [Padam87/bin-packer#2]
Hello,

Great job :D

Could add a little optimization : these algorithm can be used for truck loading. For 240 width you can put 2 pallets 120x80 or 3 pallets 80x120. 

Based on that, if your goal is to optimize the Load Meter, the following code should return [0,0][80,0][160,0] (getX, getY of each block), but it gives [0,0][120,0][0,80]. In the first result, LDM would be 120, in the second it would be 160.

`$bin = new Bin(240, 300);
    $blocks = [
        new Block(120, 80, true),
        new Block(120, 80, true),
        new Block(120, 80, true),
    ];`

Just an idea :)

**Comment by Padam87** [comment]
Hi,

There is a lot of room for improvement here, but I don't have the need for this now, so I didn't want to invest the time.

- You could limit the growth of the bin to one direction only, to enforce the 240 width.
- You could create a SortingStrategyInterface to replace the built in sort function in the packer.
- You could create a way to skip an item if it wont fit, and there is good fit in the remaining items. 

PRs are welcome.
